{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "speech-container.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "speech-container.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels: {{- include "speech-container.selectorLabels" . | nindent 6 }}
{{- end }}
